apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: url-shortener

build:
  local:
    push: false   # 🚫 DO NOT push to Docker Hub

  artifacts:
    - image: zeroop/url-shortner-auth-service
      context: services/auth-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

    - image: zeroop/url-shortner-url-service
      context: services/url-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

    - image: zeroop/url-shortner-counter-service
      context: services/counter-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

manifests:
  rawYaml:
    - infra/k8s/databases/*
    - infra/k8s/clickhouse/*
    - infra/k8s/event-bus/*
    - infra/k8s/auth-depl.yaml
    - infra/k8s/url-depl.yaml
    - infra/k8s/counter-depl.yaml
    - infra/k8s/analytics-depl.yaml
    - infra/k8s-dev/*

deploy:
  kubectl: {}