apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
data:
  config.xml: |
    <yandex>

      <!-- VERY IMPORTANT -->
      <listen_host>0.0.0.0</listen_host>

      <remote_servers>
        <my_cluster>
          <shard>
            <replica>
              <host>clickhouse-0.clickhouse</host>
              <port>9000</port>
            </replica>
            <replica>
              <host>clickhouse-1.clickhouse</host>
              <port>9000</port>
            </replica>
          </shard>
          <shard>
            <replica>
              <host>clickhouse-2.clickhouse</host>
              <port>9000</port>
            </replica>
            <replica>
              <host>clickhouse-3.clickhouse</host>
              <port>9000</port>
            </replica>
          </shard>
        </my_cluster>
      </remote_servers>

      <zookeeper>
        <node>
          <host>zookeeper</host>
          <port>2181</port>
        </node>
      </zookeeper>

      <macros>
        <cluster>my_cluster</cluster>
      </macros>

    </yandex>