# This is the reference file to setup cassandra database if needed. 
# apiVersion: v1
# kind: Service
# metadata:
#   name: cassandra
# spec:
#   clusterIP: None
#   publishNotReadyAddresses: true
#   selector:
#     app: cassandra
#   ports:
#     - port: 9042
# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: cassandra
# spec:
#   serviceName: cassandra
#   replicas: 3
#   podManagementPolicy: OrderedReady
#   selector:
#     matchLabels:
#       app: cassandra
#   template:
#     metadata:
#       labels:
#         app: cassandra
#     spec:
#       containers:
#         - name: cassandra
#           image: cassandra:4.1
#           resources:
#             requests:
#               memory: "800Mi"
#               cpu: "250m"
#             limits:
#               memory: "1Gi" # Hard cap at 1GB per node (Total 3GB)
#           env:
#             - name: CASSANDRA_CLUSTER_NAME
#               value: "cluster"
#             - name: CASSANDRA_SEEDS
#               value: "cassandra-0.cassandra"
#             # CRITICAL: Force the JVM to stay small
#             - name: MAX_HEAP_SIZE
#               value: "512M"
#             - name: HEAP_NEWSIZE
#               value: "100M"
#           volumeMounts:
#             - name: data
#               mountPath: /var/lib/cassandra
#   volumeClaimTemplates:
#     - metadata:
#         name: data
#       spec:
#         accessModes: ["ReadWriteOnce"]
#         resources:
#           requests:
#             storage: 500Mi

# import { app } from "./app";
# import { redisClient } from "./redis-client";
# import { cassandraWrapper } from "./cassandra-wrapper";

# const start = async () => {
#     // 1. Env Checks
#     if (!process.env.CASSANDRA_CONTACT_POINTS || !process.env.CASSANDRA_LOCAL_DC) {
#         throw new Error("CASSANDRA_CONTACT_POINTS and CASSANDRA_LOCAL_DC must be defined");
#     }

#     const contactPoints = process.env.CASSANDRA_CONTACT_POINTS.split(',');

#     // 2. Initialize Redis
#     console.log('[url] Initializing Redis...');
#     await redisClient.ping();

#     // 3. Connect Cassandra (The Wrapper now handles the retry loop internally)
#     try {
#         await cassandraWrapper.connect(
#             contactPoints, 
#             process.env.CASSANDRA_LOCAL_DC, 
#             process.env.CASSANDRA_KEYSPACE
#         );

#         // 4. Log the state once connected
#         const hosts = cassandraWrapper.client.getState().getConnectedHosts();
#         hosts.forEach(h => console.log(`Connected to host: ${h.address}`));
#     } catch (err) {
#         console.error("Fatal: Could not connect to Cassandra", err);
#         process.exit(1);
#     }

#     // 5. Start App
#     app.listen(3000, () => {
#         console.log("URL Service is listening on port 3000");
#     });
# }

# start();