apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url
  template:
    metadata:
      labels:
        app: url
    spec:
      containers:
        - name: url
          image: zeroop/url-shortner-url-service   
          env:
            - name: COUNTER_SERVICE_URL
              value: "http://counter-srv:3000"
          envFrom:
            - secretRef:
                name: url-mongo-secrets
            - secretRef:
                name: cassandra-secrets
            - secretRef:
                name: redis-secrets 

          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: url-srv
spec:
  selector:
    app: url
  ports:
    - name: url
      protocol: TCP
      port: 3000
      targetPort: 3000