apiVersion: v1
kind: ConfigMap
metadata:
  name: counter-redis-config
data:
  redis.conf: |
    appendonly yes
    appendfsync always 
    save ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counter-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-redis-depl
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: counter-redis
  template:
    metadata:
      labels:
        app: counter-redis
    spec:
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: counter-redis-pvc
        - name: config
          configMap:
            name: counter-redis-config
      containers:
        - name: redis
          image: redis:7-alpine
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
            - name: config
              mountPath: /usr/local/etc/redis/
---
apiVersion: v1
kind: Service
metadata:
  name: counter-redis-srv
spec:
  selector:
    app: counter-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379